[package]
authors = ["Henrik Tougaard <henrik@adaptagency.com>"]
name = "axum-otlp-honeycomb"
version = "0.3.0"
edition = "2021"

[dependencies]
opentelemetry-otlp = { version = "0.27", features = [
    "reqwest-client",
    "reqwest-rustls",
    "http-proto",
], default-features = false }
opentelemetry = { version = "0.27", features = [
    "trace",
], default-features = false }
opentelemetry-http = "0.27"
opentelemetry_sdk = { version = "0.27", features = [
    "trace",
    "rt-tokio",
], default-features = false }
tracing-opentelemetry = "0.28"
tracing-core = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
pin-project-lite = "0.2"
http = "1"
tower = "0.5"
tracing = "0.1"
futures-util = "0.3"
axum = "0.7"
clap = { version = "4", features = ["cargo"] }
