[package]
authors = ["Henrik Tougaard <henrik@adaptagency.com>"]
name = "axum-otlp-honeycomb"
version = "0.6.0"
edition = "2024"

[dependencies]
axum = "0.8"
futures-util = "0.3"
http = "1"
opentelemetry = { version = "0.32", features = [
    "trace",
], default-features = false }
opentelemetry-appender-tracing = "0.32"
opentelemetry-http = "0.32"
opentelemetry-otlp = { version = "0.32", features = [
    "reqwest-blocking-client",
    "reqwest-rustls",
    "http-proto",
    "logs",
], default-features = false }
opentelemetry_sdk = { version = "0.32", features = [
    "trace",
    "rt-tokio",
], default-features = false }
opentelemetry-semantic-conventions = { version = "0.32.0", features = ["semconv_experimental"] }
pin-project-lite = "0.2"
thiserror = "2"
tower = "0.5"
tracing = "0.1"
tracing-core = "0.1"
tracing-opentelemetry = "0.33"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2" }
